require("plugins")
require("lualine-config")
require("options")
require("treesitter-config")
require('bufferline-config')
require("nvim-web-devicons")
require("keymaps")
require("telescope-config") -- https://github.com/nvim-telescope/telescope.nvim
require("whichkey")
require("lsp")
-- require("undo-tree-config")
require("gitsigns-config")
require("toggle-term-config")
require("kanagawa-config")
require("lspsaga-config")
require("harpoon-config")
require("none-ls-config")
require("colors")
require("noice-config")
-- require('neotree-config')
require("comment-config")
require("nvim-surround-config")
require("lab-config")
require("illuminate-config")
require("dashboard-config")
require("ufo-config")
require("oil-config")
require("flash-config")
require("dap-config")
require("icons")
require("indentline-config")
require("autopair-config")
require("autocmd-config")
require("cmp-config")
-- require("copilot-config")
-- require("eyeliner-config")
require("neoscroll-config")
require("numb-config")
-- require("tabby-config")
require("neo-tab-config")
-- require("fzf-config")
require("highlight-config")
